- name: Deploy Hudini Project with Anaconda
  hosts: localhost
  become: true

  vars:
    conda_path: "/root/anaconda3/bin"  # Path to your Anaconda installation
    project_path: "/var/www/hudini"   # Path to the project directory
    requirements_path: "/var/www/hudini/server/requirements.txt"  # Path to the requirements.txt

  tasks:
    - name: Ensure the hudini user exists
      user:
        name: hudini
        shell: /bin/bash
        state: present
        home: /home/hudini
        create_home: yes

    - name: Ensure system dependencies are installed
      apt:
        name:
          - python3  # Optional, for non-Conda tasks
        state: present
        update_cache: yes

    - name: Check if the hudini Conda environment exists
      shell: |
        {{ conda_path }}/conda env list | grep -w hudini
      register: conda_env_check
      failed_when: false

    - name: Create the hudini Conda environment if it doesn't exist
      shell: |
        {{ conda_path }}/conda create -n hudini python=3.10 -y
      when: conda_env_check.rc != 0

    - name: Install Python dependencies in the hudini Conda environment
      shell: |
        source {{ conda_path }}/activate hudini && pip install -r {{ requirements_path }}
      args:
        executable: /bin/bash
        chdir: "{{ project_path }}"

    - name: Set ownership for the project directory
      file:
        path: "{{ project_path }}"
        owner: hudini
        group: hudini
        recurse: yes

    - name: Set permissions for the project directory
      file:
        path: "{{ project_path }}"
        mode: '0755'
